export const ADD_TEAM = 'ADD_TEAM';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL';
export const ADD_TEAM_START = 'ADD_TEAM_START';
export const REMOVE_MATCH_START = 'REMOVE_MATCH_START';
export const REMOVE_MATCH_FAIL = 'REMOVE_MATCH_FAIL';
export const REMOVE_MATCH_SUCCESS = 'REMOVE_MATCH_SUCCESS';

export const GET_TEAM = 'GET_TEAM';
export const GET_TEAM_START = 'GET_TEAM_START';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL';
export const UPDATE_SELECTED_TEAM = 'UPDATE_SELECTED_TEAM';

export const ADD_PLAYER_TO_TEAM = 'ADD_PLAYER_TO_TEAM';
export const ADD_PLAYER_TO_TEAM_SUCCESS = 'ADD_PLAYER_TO_TEAM_SUCCESS';
export const ADD_PLAYER_TO_TEAM_START = 'ADD_PLAYER_TO_TEAM_START';
export const ADD_PLAYER_TO_TEAM_FAIL = 'ADD_PLAYER_TO_TEAM_FAIL';

export const ADD_MATCH_START = 'ADD_MATCH_START';
export const ADD_MATCH_SUCCESS = 'ADD_MATCH_SUCCESS';
export const ADD_MATCH_FAIL = 'ADD_MATCH_FAIL';
export const SET_SELECTED_TEAM = 'SET_SELECTED_TEAM';
export const SET_MATCH_INFO = 'SET_MATCH_INFO';
export const SET_MATCH_PLAYERS = 'SET_MATCH_PLAYERS';
export const SET_MATCH_PLAYERS_SUCCESS = 'SET_MATCH_PLAYERS_SUCCESS';
export const SET_MATCH_PLAYERS_FAIL = 'SET_MATCH_PLAYERS_FAIL';
export const SET_MATCH_PLAYERS_START = 'SET_MATCH_PLAYERS_START';
export const GET_MATCH_PLAYERS_START = 'SET_MATCH_PLAYERS_START';
export const GET_MATCH_PLAYERS_FAIL = 'GET_MATCH_PLAYERS_FAIL';
export const GET_MATCH_PLAYERS_SUCCESS = 'GET_MATCH_PLAYERS_SUCCESS';
export const SAVE_MATCHSTATS_START = 'SAVE_MATCHSTATS_START';
export const SAVE_MATCHSTATS_SUCCESS = 'SAVE_MATCHSTATS_SUCCESS';
export const SAVE_MATCHSTATS_FAIL = 'SAVE_MATCHSTATS_FAIL';
export const OPONENTGOAL_UPDATE = 'OPONENTGOAL_UPDATE';
export const SET_FALSE_SAVE_STATE = 'SET_FALSE_SAVE_STATE';

export const NAVPANEL_SELECTION = 'NAVPANEL_SELECTION'
export const SIDEPANEL_TOGGLE = 'SIDEPANEL_TOGGLE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_COMPONENT = 'SHOW_COMPONENT';
export const SHOW_FUNCTIONMENU = 'SHOW_FUNCTIONMENU';
export const LOCATION_CHANGE = 'LOCATION_CHANGE';

export const SET_SELECTED_MATCH = 'SET_SELECTED_MATCH';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_FIREBASE_SUCCESS = 'AUTH_FIREBASE_SUCCESS';
export const GOOGLE_AUTH_START = 'GOOGLE_AUTH_START';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';


export const GET_ALL_TEAMS_START = 'GET_ALL_TEAMS_START'; 
export const GET_ALL_TEAMS_SUCCESS = 'GET_ALL_TEAMS_SUCCESS'; 
export const GET_ALL_TEAMS_FAIL = 'GET_ALL_TEAMS_FAIL'; 
export const REMOVE_PLAYER_START = 'REMOVE_PLAYER_START';
export const REMOVE_PLAYER_SUCCESS = 'REMOVE_PLAYER_SUCCESS';
export const REMOVE_PLAYER_FAIL = 'REMOVE_PLAYER_FAIL';
export const SET_SEASON = 'SET_SEASON';
export const UPDATE_PLAYER_ADMIN = 'UPDATE_PLAYER_ADMIN';
export const UPDATE_PLAYER_ADMIN_START = 'UPDATE_PLAYER_ADMIN_START';
export const UPDATE_PLAYER_ADMIN_FAIL = 'UPDATE_PLAYER_ADMIN_FAIL';
export const UPDATE_PLAYER_ADMIN_SUCCESS = 'UPDATE_PLAYER_ADMIN_SUCCESS';

export const SET_LAST_SELECTED_TEAM_START = 'SET_LAST_SELECTED_TEAM_START'
export const SET_LAST_SELECTED_TEAM_FAIL = 'SET_LAST_SELECTED_TEAM_FAIL'
export const SET_LAST_SELECTED_TEAM_SUCCESS = 'SET_LAST_SELECTED_TEAM_SUCCESS'

export const GET_LAST_SELECTED_TEAM_START = 'GET_LAST_SELECTED_TEAM_START'
export const GET_LAST_SELECTED_TEAM_FAIL = 'GET_LAST_SELECTED_TEAM_FAIL'
export const GET_LAST_SELECTED_TEAM_SUCCESS = 'GET_LAST_SELECTED_TEAM_SUCCESS'

export const ADD_SEASON_SUCCESS = 'ADD_SEASON_SUCCESS'
export const ADD_SEASON_START = 'ADD_SEASON_START'
export const ADD_SEASON_FAIL = 'ADD_SEASON_FAIL'

export const GET_FOLLOWEDTEAMS_START = 'GET_FOLLOWEDTEAMS_START'
export const GET_FOLLOWEDTEAMS_SUCCESS = 'GET_FOLLOWEDTEAMS_SUCCESS'
export const GET_FOLLOWEDTEAMS_FAIL = 'GET_FOLLOWEDTEAMS_FAIL'

export const SET_FOLLOWEDTEAMS_START = 'SET_FOLLOWEDTEAMS_START'
export const SET_FOLLOWEDTEAMS_SUCCESS = 'SET_FOLLOWEDTEAMS_SUCCESS'
export const SET_FOLLOWEDTEAMS_FAIL = 'SET_FOLLOWEDTEAMS_FAIL'