export const ADD_TEAM = 'ADD_TEAM';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL';
export const ADD_TEAM_START = 'ADD_TEAM_START';

export const GET_TEAM = 'GET_TEAM';
export const GET_TEAM_START = 'GET_TEAM_START';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL';

export const NAVPANEL_SELECTION = 'NAVPANEL_SELECTION'
export const SIDEPANEL_TOGGLE = 'SIDEPANEL_TOGGLE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_COMPONENT = 'SHOW_COMPONENT';
export const SHOW_FUNCTIONMENU = 'SHOW_FUNCTIONMENU';
