export const ADD_TEAM = 'ADD_TEAM';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL';
export const ADD_TEAM_START = 'ADD_TEAM_START';

export const GET_TEAM = 'GET_TEAM';
export const GET_TEAM_START = 'GET_TEAM_START';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL';

export const ADD_PLAYER_TO_TEAM = 'ADD_PLAYER_TO_TEAM';
export const ADD_PLAYER_TO_TEAM_SUCCESS = 'ADD_PLAYER_TO_TEAM_SUCCESS';
export const ADD_PLAYER_TO_TEAM_START = 'ADD_PLAYER_TO_TEAM_START';
export const ADD_PLAYER_TO_TEAM_FAIL = 'ADD_PLAYER_TO_TEAM_FAIL';

export const SET_SELECTED_TEAM = 'SET_SELECTED_TEAM';

export const NAVPANEL_SELECTION = 'NAVPANEL_SELECTION'
export const SIDEPANEL_TOGGLE = 'SIDEPANEL_TOGGLE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_COMPONENT = 'SHOW_COMPONENT';
export const SHOW_FUNCTIONMENU = 'SHOW_FUNCTIONMENU';

export const SET_SELECTED_MATCH = 'SET_SELECTED_MATCH';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_FIREBASE_SUCCESS = 'AUTH_FIREBASE_SUCCESS';

export const GET_ALL_TEAMS_START = 'GET_ALL_TEAMS_START'; 
export const GET_ALL_TEAMS_SUCCESS = 'GET_ALL_TEAMS_SUCCESS'; 
export const GET_ALL_TEAMS_FAIL = 'GET_ALL_TEAMS_FAIL'; 
